/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AccueilPackage;

import java.awt.CardLayout;
import java.sql.*;


import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter; 
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

   

// ekhdm aal dashboard fil accueil


/**
 *
 * @author Baha
 */
// nzid etat lel chambre w nkhadem les button dispo w non dispo
// ntaktek fazet el reservation wel jointure
// nbadel el reservation el facture 

public class Accueil extends javax.swing.JFrame {
    /**
     * Creates new form Accueil
     */

    public Accueil() {
         initComponents(); 
         
         addChart();
         //addChart();
         this.setExtendedState(MAXIMIZED_BOTH);
         //this.setUndecorated(true);

         FillTable(jTable1, "SELECT * FROM t_client;");
         FillTable(jTable3, "SELECT * FROM t_chambres;");
         FillTable(jTable4, "SELECT * FROM t_reservation;");
         jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();
         
         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
         forceDate();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
   
    public void forceDate(){
       // timeAndDate = new JFormattedTextField(date);

        
    }
    
    public void PopupalteCombo(JComboBox cmb, String Query)
        {
           try
    {
        try{
        
        Statement stat = DBConnect.getConnection().createStatement();
        ResultSet rs = stat.executeQuery(Query);
        
        while(rs.next())
        {  
           cmb.addItem(rs.getString("NUM")); 
        }

        rs.close();
        stat.close();
        DBConnect.getConnection().close();
    }
    catch(SQLException e)
    {
    }
            //JOptionPane.showMessageDialog(null, "Connecté");
        }   
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            JOptionPane.showMessageDialog(null,"non connected");
        }
 //Statement st = cn.createStatement();
        }

public boolean existsInTable(JTable table, String entry) {

    // Get row and column count
    int rowCount = table.getRowCount();
    int colCount = table.getColumnCount();

    // Get Current Table Entry
    String curEntry = "";
    String o = entry;
    String e = o.toString();
    curEntry = curEntry + " " + e;
    

    // Check against all entries
    for (int i = 0; i < rowCount; i++) {
        String rowEntry = "";
        for (int j = 0; j < colCount; j++)
            rowEntry = rowEntry + " " + table.getValueAt(i, j).toString();
        if (rowEntry.equalsIgnoreCase(curEntry)) {
            return true;
        }
    }
    return false;
}
public void clearTable(JTable jtMyTable)
{
    
    DefaultTableModel dtm = (DefaultTableModel) jtMyTable.getModel();
    dtm.setRowCount(0);
}
    public void FillTable(JTable table, String Query)
{
    try
    {
        try{

        Statement stat = DBConnect.getConnection().createStatement();
        ResultSet rs = stat.executeQuery(Query);
        while(table.getRowCount() > 0) 
        {
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) table.getModel()).insertRow(rs.getRow()-1,row);
        }

        rs.close();
        stat.close();
        DBConnect.getConnection().close();
    }
    catch(SQLException e)
    {
    }
            //JOptionPane.showMessageDialog(null, "Connecté");
        }   
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
            JOptionPane.showMessageDialog(null,"non connected");
        }


        //To remove previously added rows
        
}
 private void addChart(){
     DefaultCategoryDataset dcd = new DefaultCategoryDataset();        
        try{
        Statement stat = DBConnect.getConnection().createStatement();
        ResultSet rs = stat.executeQuery("SELECT COUNT(*), DATE_RES FROM t_reservation GROUP BY DATE_RES");
        
    while(rs.next())
        {   
             dcd.setValue(rs.getInt(1),rs.getDate("DATE_RES").toString(),rs.getDate("DATE_RES").toString() );  
        } 
        rs.close();
        stat.close();
        DBConnect.getConnection().close();
    }
    catch(SQLException e)
    {
         System.err.println("Got an exception!"+ e.getMessage());
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
       
        
        //
        JFreeChart jchart = ChartFactory.createBarChart("Volume du réservations","Dates","Nombres de réservations",dcd, PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=jchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("Volume du réservations", jchart);
        frame.setVisible(true);
        frame.setSize(800,800);
        
 }  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtClient = new javax.swing.JButton();
        jbtReservation = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jbtChambres = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtClient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtClient.setText("Gestion clients");
        jbtClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClientActionPerformed(evt);
            }
        });

        jbtReservation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtReservation.setText("Gestion de chambres");
        jbtReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtReservationActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Open Sans Light", 1, 48)); // NOI18N
        jLabel20.setText("Gestion d'hotel");

        jButton8.setText("Nombres de reservations");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton14.setText("Taux de remplissage");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(646, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel4, "card5");

        jLabel1.setText("Numéro :");

        jLabel4.setText("Prénom :");

        jLabel5.setText("Nom :");

        jLabel6.setText("CIN :");

        jLabel7.setText("Tel :");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Gestion des clients");

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero", "Prenom", "Nom", "CIN", "Telephone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel1, "card1");

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Gestion de résérvation");

        jLabel9.setText("Numéro :");

        jLabel10.setText("Numéro client :");

        jLabel11.setText("Nombre de nuits :");

        jLabel12.setText("Date de réservation :");

        jLabel13.setText("Date d'entré :");

        jLabel14.setText("Date de départ  :");

        jLabel15.setText("Nombres de personnes :");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Supprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Client", "Chambre", "NB Nuits", "NB Personne", "Date", "Entrée", "Départ"
            }
        ));
        jTable4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable4FocusLost(evt);
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Numéro chambre :");

        jButton10.setText("Générer facture");
        jButton10.setActionCommand("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)))
                                    .addComponent(jLabel14))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel2, "card2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Gestion de chambres");

        jLabel3.setText("Numéro :");

        jLabel17.setText("Type :");

        jLabel18.setText("Catégorie :");

        jLabel19.setText("Prix :");

        jButton7.setText("Modifier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero", "Type", "Catégorie", "Prix", "Etat"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Vue mer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Suite" }));

        jButton11.setText("Ajouter");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Supprimer");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel17))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 870, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel3, "card3");

        jbtChambres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtChambres.setText("Gestion de réservations");
        jbtChambres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtChambresActionPerformed(evt);
            }
        });

        jButton9.setText("Menu");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setText("Accueil");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(656, 656, 656)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jbtClient, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(jbtChambres, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jbtReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtChambres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtClient, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClientActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "card1");
         
         
    }//GEN-LAST:event_jbtClientActionPerformed

    private void jbtChambresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtChambresActionPerformed
        // TODO add your handling code here:
        //Client cc1= new Client();
        CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "card2");
    }//GEN-LAST:event_jbtChambresActionPerformed

    private void jbtReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReservationActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "card3");
    }//GEN-LAST:event_jbtReservationActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
        else if (!(jTextField4.getText().matches("[0-9]{8,8}"))){
                   JOptionPane.showMessageDialog(null, "CIN doit etre numerique et composée de 8 chifres!");

        }
       
        else{
             
        try{
        
            
      String query = "insert into t_client (PRENOM, NOM, CIN, TEL)"
        + " values (?, ?, ?, ?)";

      // create the mysql insert preparedstatement
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      //preparedStmt.setInt (1, Integer.parseInt(jTextField1.getText()));
      preparedStmt.setString (1, jTextField2.getText().toString());
      preparedStmt.setString   (2, jTextField3.getText().toString());
      preparedStmt.setInt (3, Integer.parseInt(jTextField4.getText()));
      preparedStmt.setInt (4, Integer.parseInt(jTextField5.getText()));
      // execute the preparedstatement
      preparedStmt.execute();
      
      DBConnect.getConnection().close();
         JOptionPane.showMessageDialog(null,"Client ajouté!");

       jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable1);
      FillTable(jTable1, "SELECT * FROM t_client;");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        jTextField1.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField2.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jTextField3.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jTextField4.setText(model.getValueAt(selectedRowIndex, 3).toString());
        jTextField5.setText(model.getValueAt(selectedRowIndex, 4).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner un client!");
        }
        else if (!(jTextField4.getText().matches("[0-9]{8,8}"))){
                   JOptionPane.showMessageDialog(null, "CIN doit etre numerique et composée de 8 chifres!");

        }
       
        else{
             
        try{
       
            
      String query = "UPDATE  t_client SET PRENOM = ?, NOM = ?, CIN = ?, TEL = ?"
         + " WHERE NUM=?";
      
      // create the mysql insert preparedstatement
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setString (1, jTextField2.getText());
      preparedStmt.setString (2, jTextField3.getText().toString());
      preparedStmt.setInt   (3, Integer.parseInt(jTextField4.getText().toString()));
      preparedStmt.setInt (4, Integer.parseInt(jTextField5.getText()));
      preparedStmt.setInt (5, Integer.parseInt(jTextField1.getText()));
      // execute the preparedstatement
      preparedStmt.executeUpdate();
                  JOptionPane.showMessageDialog(null,"Client modifié!");

      jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
      DBConnect.getConnection().close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable1);
      FillTable(jTable1, "SELECT * FROM t_client;");
      
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
             if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner un client!");
        }
        else if (!(jTextField4.getText().matches("[0-9]{8,8}"))){
                   JOptionPane.showMessageDialog(null, "CIN non-existant! Veuillez verifier vos informations!");

        }
       
        else{
             
        try{
        
            
      String query = "DELETE FROM t_client WHERE CIN = ?";
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setInt (1, Integer.parseInt(jTextField4.getText()));

      int dialogButton = JOptionPane.YES_NO_OPTION;
      JOptionPane.showConfirmDialog (null, "Voulez vous supprimer ce client?","Attention",dialogButton);
      
    if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here

      preparedStmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"Client supprimé!");
        
    }
    else

        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
      DBConnect.getConnection().close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable1);
      FillTable(jTable1, "SELECT * FROM t_client;");
      
              // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 if(jTextField13.getText().equals("")||jTextField16.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }  
        else{
             
        try{
       
            
      String query = "insert into t_chambres (NUM, TYPE, CAT, PRIX)"
        + " values (?, ?, ?, ?)";

      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setString (1, jTextField13.getText().toString());
      preparedStmt.setString   (2, jComboBox2.getSelectedItem().toString());
      preparedStmt.setString   (3, jComboBox1.getSelectedItem().toString());
      preparedStmt.setDouble (4, Double.parseDouble(jTextField16.getText()));
      // execute the preparedstatement
      preparedStmt.execute();
      
      DBConnect.getConnection().close();
         JOptionPane.showMessageDialog(null,"Chambres ajouté!");

       jTextField13.setText(null);
        jTextField16.setText(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
  
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
                             // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 if(jTextField13.getText().equals("")||jTextField16.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner une chambre!");
        }
       
        else{
             
        try{
       
      String query = "UPDATE  t_chambres SET NUM = ?, TYPE = ?, CAT = ?, PRIX = ?"
         + " WHERE NUM=?";

      // create the mysql insert preparedstatement
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setString (1, jTextField13.getText().toString());
      preparedStmt.setString   (2, jComboBox2.getSelectedItem().toString());
      preparedStmt.setString   (3, jComboBox1.getSelectedItem().toString());
      preparedStmt.setDouble (4, Double.parseDouble(jTextField16.getText()));
      preparedStmt.setString (5, jTextField13.getText().toString());

      // execute the preparedstatement
      preparedStmt.executeUpdate();
                  JOptionPane.showMessageDialog(null,"Chambre modifié!");

      jTextField13.setText(null);
      jTextField16.setText(null);
      DBConnect.getConnection().close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
      jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
 DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int selectedRowIndex = jTable3.getSelectedRow();
        jTextField13.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jComboBox2.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
        jComboBox1.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
        jTextField16.setText(model.getValueAt(selectedRowIndex, 3).toString());
                // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
             if(jTextField13.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Vous devez selectionner une chambre!");
        }     
        else{           
        try{
                
      String query = "DELETE FROM t_chambres WHERE NUM = ?";

      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setInt (1, Integer.parseInt(jTextField13.getText()));
      // execute the preparedstatement
      int dialogButton = JOptionPane.YES_NO_OPTION;
      JOptionPane.showConfirmDialog (null, "Voulez vous supprimer cette chambre?","Attention",dialogButton);

    if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here

      preparedStmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"Chambre supprimé!");
         jTextField13.setText(null);
        jTextField16.setText(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
    
    }
    else

       
      DBConnect.getConnection().close();
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
 DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int selectedRowIndex = jTable4.getSelectedRow();
        jTextField6.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField8.setText(model.getValueAt(selectedRowIndex, 3).toString());
        jTextField9.setText(model.getValueAt(selectedRowIndex, 4).toString());
        jTextField12.setText(model.getValueAt(selectedRowIndex, 5).toString());
        jTextField7.setText(model.getValueAt(selectedRowIndex, 6).toString());
        jTextField10.setText(model.getValueAt(selectedRowIndex, 7).toString());
        jComboBox3.setSelectedItem(model.getValueAt(selectedRowIndex, 1).toString());
        jComboBox4.setSelectedItem(model.getValueAt(selectedRowIndex, 2).toString());
        
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 if(jTextField8.getText().equals("")||jTextField9.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
        
       else if (!(jTextField8.getText().matches("[1-9]{1,3}")||!(jTextField9.getText().matches("[1-9]{1,8}")))){
                   JOptionPane.showMessageDialog(null, "Vous devez inserer un chiffre");

        }
       
        else{
             
        try{
        
            
      String query = "INSERT into t_reservation (NUMCL, NUMCH, NB_NUIT, NB_PERSONNE, DATE_RES, CHECK_IN, CHECK_OUT)"
        + " values (?, ?, ?, ?, ?, ?, ?);";
      
      String query2 = "UPDATE t_chambres SET ETAT='RESERVE' WHERE NUM=?;";
      PreparedStatement preparedStmt2 = DBConnect.getConnection().prepareStatement(query2);
      preparedStmt2.setInt (1, Integer.parseInt(jComboBox4.getSelectedItem().toString()));
      preparedStmt2.execute();
      
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setInt (1, Integer.parseInt(jComboBox3.getSelectedItem().toString()));
      preparedStmt.setInt (2, Integer.parseInt(jComboBox4.getSelectedItem().toString()));
      preparedStmt.setInt (3, Integer.parseInt(jTextField8.getText()));
      preparedStmt.setInt (4, Integer.parseInt(jTextField9.getText()));
      preparedStmt.setDate   (5, java.sql.Date.valueOf(jTextField12.getText()));
      preparedStmt.setDate   (6, java.sql.Date.valueOf(jTextField7.getText()));    
      preparedStmt.setDate   (7, java.sql.Date.valueOf(jTextField10.getText()));
      
      // execute the preparedstatement
      preparedStmt.execute();
      
      DBConnect.getConnection().close();
         JOptionPane.showMessageDialog(null,"Reservation ajouté!");

       jTextField6.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jComboBox3.setSelectedItem(null);
        jComboBox4.setSelectedItem(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!"+ e.getMessage());
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable4);
      FillTable(jTable4, "SELECT * FROM t_reservation;");
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(jTextField8.getText().equals("")||jTextField9.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
        
       else if (!(jTextField8.getText().matches("[1-9]{1,3}")||!(jTextField9.getText().matches("[1-9]{1,8}")))){
                   JOptionPane.showMessageDialog(null, "Vous devez inserer un chiffre");

        }
       
        else{
             
        try{
        String query = "UPDATE t_reservation SET NUMCL=?, NUMCH=?, NB_NUIT=?, NB_PERSONNE=?, DATE_RES=?, CHECK_IN=?, CHECK_OUT=?"
        + " WHERE NUM = ? ";
      
      String query2 = "UPDATE t_chambres SET ETAT='RESERVE' WHERE NUM=?;";
      PreparedStatement preparedStmt2 = DBConnect.getConnection().prepareStatement(query2);
       preparedStmt2.setInt (1, Integer.parseInt(jComboBox4.getSelectedItem().toString()));

      preparedStmt2.execute();
      

      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setInt (1, Integer.parseInt(jComboBox3.getSelectedItem().toString()));
      preparedStmt.setInt (2, Integer.parseInt(jComboBox4.getSelectedItem().toString()));
      preparedStmt.setInt (3, Integer.parseInt(jTextField8.getText()));
      preparedStmt.setInt (4, Integer.parseInt(jTextField9.getText()));
      preparedStmt.setDate   (5, java.sql.Date.valueOf(jTextField12.getText()));
      preparedStmt.setDate   (6, java.sql.Date.valueOf(jTextField7.getText()));    
      preparedStmt.setDate   (7, java.sql.Date.valueOf(jTextField10.getText()));
      preparedStmt.setInt (8, Integer.parseInt(jTextField6.getText()));
      
      // execute the preparedstatement
      preparedStmt.execute();
      
      DBConnect.getConnection().close();
         JOptionPane.showMessageDialog(null,"Reservation modifié!");

       jTextField6.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jComboBox3.setSelectedItem(null);
        jComboBox4.setSelectedItem(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable4);
      FillTable(jTable4, "SELECT * FROM t_reservation;");
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
          // TODO add your handling code here:
                        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(jTextField8.getText().equals("")||jTextField9.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une reservation a supprimer!");
        }
        
       else if (!(jTextField8.getText().matches("[1-9]{1,3}")||!(jTextField9.getText().matches("[1-9]{1,8}")))){
                   JOptionPane.showMessageDialog(null, "Vous devez inserer un chiffre");

        }
       
        else{
             
        try{
        
        String query = "DELETE FROM t_reservation WHERE NUM =?;";
      
      String query2 = "UPDATE t_chambres SET ETAT='NON-RESERVE' WHERE NUM=?;";
      PreparedStatement preparedStmt2 = DBConnect.getConnection().prepareStatement(query2);
      preparedStmt2.setInt (1, Integer.parseInt(jComboBox4.getSelectedItem().toString()));
      preparedStmt2.execute();    
      PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
      preparedStmt.setInt (1, Integer.parseInt(jTextField6.getText().toString()));
          preparedStmt.execute();
        JOptionPane.showMessageDialog(null,"Reservation supprimé!");
      DBConnect.getConnection().close();

       jTextField6.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        //jTextField12.setText(null);
        //jTextField10.setText(null);
        //jTextField11.setText(null);
        jComboBox3.setSelectedItem(null);
        jComboBox4.setSelectedItem(null);
        jComboBox3.removeAllItems();
         jComboBox4.removeAllItems();

         PopupalteCombo(jComboBox3, "SELECT NUM from t_client;");
         PopupalteCombo(jComboBox4, "SELECT NUM from t_chambres;");
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
 
        
        }
        
      clearTable(jTable4);
      FillTable(jTable4, "SELECT * FROM t_reservation;");
      clearTable(jTable3);
      FillTable(jTable3, "SELECT * FROM t_chambres;");
          // TODO add your handling code here:
                        // TODO add your handling code here:
                              // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
       
        if(jTextField6.getText().equals("")||jComboBox4.getSelectedItem().toString().equals("")||jComboBox3.getSelectedItem().toString().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une reservation pour generer une facture!");
        }
       
        else{
           
       
        String prenom = null, nom = null;
        String date=jTextField7.getText().toString();
        String date_r=jTextField12.getText().toString();
        int num_res=Integer.parseInt(jTextField6.getText());
        double nb_nuits=Integer.parseInt(jTextField8.getText());
        int n_chambre= Integer.parseInt(jComboBox4.getSelectedItem().toString());
        double prix = 0;
        int CIN = 0;
        
        
        
        try {
            Document document = new Document();
            @SuppressWarnings("unused")
            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream("Facture.pdf"));
            document.open();
            //values to get NOM PRENOM CIN
            String query = "SELECT PRENOM, NOM, CIN from t_client WHERE NUM=?;";
            PreparedStatement preparedStmt = DBConnect.getConnection().prepareStatement(query);
            preparedStmt.setInt(1, Integer.parseInt( jComboBox3.getSelectedItem().toString()));
            ResultSet rs = preparedStmt.executeQuery();
            
        while(rs.next()){
            prenom = rs.getString(1);
            nom = rs.getString(2);
            CIN = rs.getInt(3);
        
        }
        String query2 = "SELECT PRIX from t_chambres WHERE NUM=?;";
        PreparedStatement preparedStmt2 = DBConnect.getConnection().prepareStatement(query2);
        preparedStmt2.setInt(1, Integer.parseInt(jComboBox4.getSelectedItem().toString()));
        ResultSet rs2 = preparedStmt2.executeQuery();
            
        while(rs2.next()){
            prix = rs2.getDouble(1);

        
        }         

            
            //NUM RES DATE ENTREE NB NUIT NB CHAMBRE
            // Calcul total (PRIX * NB NUITS)
            
            //
            Paragraph paragraph = new Paragraph();

            paragraph.add("FACTURE");
            paragraph.setAlignment(Element.ALIGN_CENTER);
            Paragraph otherParagraph = new Paragraph();
            otherParagraph.add("HOTEL DBEYBIA ******");
            otherParagraph.setAlignment(Element.ALIGN_CENTER);
            DottedLineSeparator dottedline = new DottedLineSeparator();
            dottedline.setOffset(-2);
            dottedline.setGap(2f);
         
            otherParagraph.add(dottedline);
     
        // info clients
            Paragraph line = new Paragraph();
            line.add("\nNom : "+ nom +  "\nPrenom : "+ prenom +"\nCIN: "+ CIN + "\n");
            line.add(dottedline);           
        // info reser
            Paragraph line2 = new Paragraph();
            line2.add("\nNumero reservation : " + num_res + "\nDate réservation : "+ date_r + "\nDate d'entrée : "+ date +"\nNombre nuits: "
                    + nb_nuits + "\nNumero chambre : " +n_chambre +"\n");
            line2.add(dottedline);
        // info total
            Paragraph line3 = new Paragraph();
            line3.add("\nTotal a payer : \n" + (prix*nb_nuits)+"\n");
            line3.add(dottedline);       
        //
            document.add(paragraph);
            document.add(otherParagraph);
            document.add(line);
            document.add(line2);
            document.add(line3);
            document.close();
            //
            File htmlFile = new File("Facture.pdf");
            Desktop.getDesktop().browse(htmlFile.toURI());
            
         
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }

   
 
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private DefaultPieDataset DefaultPieDataset() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private ChartFrame ChartFrame(String pie_Chart, JFreeChart chart) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
static class Article{
    int SNO;
    String description;
    int quantity;
    double unitPrice;
    public Article(int SNO, String description, int quantity, double unitPrice)
    {
        this.SNO = SNO;
        this.description = description;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
}
public static void addTitle(PdfWriter layoutDocument) throws DocumentException
{
    layoutDocument.add(new Paragraph("RETAIL INVOICE"));
}
public static void addCustomerReference(PdfWriter layoutDocument) throws DocumentException
{
    layoutDocument.add(new Paragraph("M/s Indian Convent School"));
    //layoutDocument.add(new Paragraph("y Pocket-3, Sector-24, Rohini Delhi-110085").setMultipliedLeading(.2f));
    //layoutDocument.add(new Paragraph("b 011-64660271").setMultipliedLeading(.2f));
}
 public void addTable(PdfWriter layoutDocument, List<Article> articleList) throws DocumentException
{
    PdfPTable table = new PdfPTable(new float[]{60f, 180f, 50f, 80f, 110f});

    // headers
    table.addCell(new Paragraph("S.N.O."));
    table.addCell(new Paragraph("PARTICULARS"));
    table.addCell(new Paragraph("QTY"));
    table.addCell(new Paragraph("RATE"));
    table.addCell(new Paragraph("AMOUNT IN RS."));

    // items
    for(Article a : articleList)
    {
        table.addCell(new Paragraph(a.SNO+""));
        table.addCell(new Paragraph(a.description));
        table.addCell(new Paragraph(a.quantity+""));
        table.addCell(new Paragraph(a.unitPrice+""));
        table.addCell(new Paragraph((a.quantity * a.unitPrice)+""));
    }

    layoutDocument.add(table);
}
    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel2FocusGained

    private void jTable4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable4FocusLost


    }//GEN-LAST:event_jTable4FocusLost

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "card5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();        
        try{
        Statement stat = DBConnect.getConnection().createStatement();
        ResultSet rs = stat.executeQuery("SELECT COUNT(*), DATE_RES FROM t_reservation GROUP BY DATE_RES");
        
    while(rs.next())
        {   
             dcd.setValue(rs.getInt(1),rs.getDate("DATE_RES").toString(),rs.getDate("DATE_RES").toString() );  
        } 
        rs.close();
        stat.close();
        DBConnect.getConnection().close();
    }
    catch(SQLException e)
    {
         System.err.println("Got an exception!"+ e.getMessage());
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
       
        
        //
        JFreeChart jchart = ChartFactory.createBarChart("Volume du réservations","Dates","Nombres de réservations",dcd, PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=jchart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("Volume du réservations", jchart);
        frame.setVisible(true);
        frame.setSize(800,400);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4FocusGained

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "card5");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
try{
        Statement stat = DBConnect.getConnection().createStatement();
        ResultSet rs = stat.executeQuery("SELECT COUNT(*) from t_chambres WHERE ETAT='RESERVE'");
        rs.next();

        int t_reser = rs.getInt(1);
        ResultSet rs2 = stat.executeQuery("SELECT COUNT(*) from t_chambres");
        rs2.next();

        int t_total = rs2.getInt(1);
        
        Double tnr = new Double(t_total);
        Double tr =  new Double(t_reser);
        
        Double taux = new Double ( (tr)/(tnr)) * 100;
        
       JOptionPane.showMessageDialog(null,"Le taux du remplissage de votre hotel est : "+taux+"%\n Vous avez :\n"+t_reser +" chambres reservéés.\n"
               + (t_total -t_reser) +" chambres non reservées.");

   
        rs.close();
        stat.close();
        DBConnect.getConnection().close();
    }
    catch(SQLException e)
    {
         System.err.println("Got an exception!"+ e.getMessage());
      JOptionPane.showMessageDialog(null,e.getMessage());
    }
       
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbtChambres;
    private javax.swing.JButton jbtClient;
    private javax.swing.JButton jbtReservation;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
